# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build
    
    # Temporary run eslint by itself as `yarn lint` is not working at the moment
    - run: ./node_modules/.bin/eslint .
    - run: yarn lint
      continue-on-error: true # Ignore failure untill fixed
      
    - run: yarn test-only
      continue-on-error: true # Ignore failure untill fixed

    - name: e2e tests
      run: cd end_to_end_tests/data && ./run-ubuntu.sh
